### PR TITLE
Add webservice to assign and find attribute def actions.

### PR DESCRIPTION
**Pull request by sachdeva-vivek**
Please ignore travis.yml.

### CODE REVIEW

**Comment by sachdeva-vivek** [comment]
This pull request has the old commits also. Please ignore them. The first commit related to WS is: Add rest lite request to get attribute assign actions

**Comment by mmoayyed** [comment]
You need to merge with master once and resolve the conflicts.

**Comment by sachdeva-vivek** [comment]
I have tried to format all the new methods with Grouper formatting xml file. I might have missed some. Please let me know if you see any. Thanks

**Comment by mchyzer** [comment]
Thanks a lot Vivek, this looks great and is a substantial contribution!

**Pull request merged**
