### PR TITLE
GRP-1108 Option to turn on/off admin/lite ui links

### PR DESCRIPTION
**Pull request by mmoayyed**
JIRA https://bugs.internet2.edu/jira/browse/GRP-1108

### CODE REVIEW

**Comment by mchyzer** [comment]
Im sorry to be a pain, but can we just do <c:if> tags instead?  Dynamically showing with javascript I think is not what we want to do here...   thanks

**Comment by mchyzer** [comment]
didnt show up.  c:if tags

**Comment by mmoayyed** [comment]
Sure. Will update.

P.S: You could use code tags for formatting stuff like that. See my edit above, or something like:

```java
System.out.println("Hello Grouper");
```

**Comment by mmoayyed** [comment]
Updated pull with tags.

**Pull request merged**
