### PR TITLE
GRP-1151 Use ldap.properties for ldap connection pooling

### PR DESCRIPTION
**Pull request by sachdeva-vivek**

### CODE REVIEW

**Comment by langedb** [comment]
Along the lines of this PR is also [GRP-1148](https://bugs.internet2.edu/jira/browse/GRP-1148).  Have you checked to ensure that setting this up won't introduce 1148's bug into the subjectAdapter?

**Comment by mchyzer** [comment]
Looks great, thanks

**Comment by mchyzer** [comment]
Whoops, Dave, missed your comment, can you explain more?  You think there is more to do here?  I was going to make a patch and let the person who was having problems test out some config arrangements to see if they can address it.

**Comment by langedb** [comment]
My concern is about 1148 where, while we provide a way to configure a LDAP connection pool, we don't provide a way to configure a validator for that pool.  This leads to the entire pool becoming invalidated if the connections are all pre-maturely terminated by the service.  I recently ran into this issue at an institution with a 30 second idle connection kill.

**Comment by mmoayyed** [comment]
I think the ldap library supports validations, with settings like 

```
ldap.pool.validateOnCheckout=false
ldap.pool.validatePeriodically=true
```

I dont know if these are documented in the config file. Note that validation on checkout does have a bit performance overhead. So we need to decide on a reasonable default.

**Comment by langedb** [comment]
It's a bit more than just those two settings.  You have to ensure that a validation method is also configured, else you get GRP-1148

**Comment by mmoayyed** [comment]
Elaborate, please. As far as I know, both VT LDAP and Spring LDAP support validation of ldap objects out of pool, and it's just matter of simple prop config. What is missing? Are you saying validation is not "on" by default?

**Comment by langedb** [comment]
See: https://code.google.com/p/vt-middleware/wiki/vtldapPooling#Validation

In 1148, there is no way to configure how to validate or even which validation class to use.  Shibboleth solves this with some custom Spring work in their DataConnector.  Unfortunately, I don't see any of that wiring for Grouper.  Hence my concern as the PSP doesn't seem to carry forward shib's method of configuring the validation of the pool.

**Comment by sachdeva-vivek** [comment]
Under GRP-1151, we are building LdapPoolConfig object with the settings defined in the ldap.properties file. LdapPoolConfig will use the defaults for the properties not defined in the ldap.properties. I think these are all the properties

 edu.vt.middleware.ldap.pool.validateOnCheckIn
edu.vt.middleware.ldap.pool.validateOnCheckOut
edu.vt.middleware.ldap.pool.validatePeriodically
edu.vt.middleware.ldap.pool.validateTimerPeriod
edu.vt.middleware.ldap.pool.pruneTimerPeriod
edu.vt.middleware.ldap.pool.expirationTime
edu.vt.middleware.ldap.pool.minPoolSize
edu.vt.middleware.ldap.pool.maxPoolSize

**Comment by langedb** [comment]
Yes, those are all the properties, however, from what I can tell, unless you also configure when you create the connections an actual pool validator, then it's useless to specify when to validate.

**Comment by mchyzer** [comment]
I committed this to address the problem, ok?

https://github.com/Internet2/grouper/commit/6342874a72e694416a513605ddb5945da8c1d553

**Comment by langedb** [comment]
Yes, perfect.  

Thanks

**Pull request merged**
