### PR TITLE
Remove dangling html element

### PR DESCRIPTION
**Pull request by mmoayyed**
Removes the dangling "--->" from the initial index page.

### CODE REVIEW

**Comment by mchyzer** [comment]
I dont understand why that was removed.. its something for people to click on if the auto redirect doesnt work for whatever reason

**Comment by mmoayyed** [comment]
ah, ok. In that case, shall we rename the link to something a bit more descriptive? On the page right now, it sort of looks like malformed html.

**Comment by mchyzer** [comment]
Its a tough one because it is static HTML and we want externalized text if we put a word there... so I was thinking the arrow was something that wouldnt need translating.  Maybe we could do font awesome character...  suggestions?

**Comment by langedb** [comment]
Perhaps &rarr; ?

**Comment by mchyzer** [comment]
something like that works for me :)

**Comment by mmoayyed** [comment]
Sure. Updated pull with @langedb's suggestion

**Pull request merged**
