### PR TITLE
auto select the folder/group/attrdef in the view

### PR DESCRIPTION
**Pull request by mmoayyed**
https://bugs.internet2.edu/jira/browse/GRP-1119

- parse the url to determine the id
- expand the view on load
- select the node based on id and make sure everything else is collapsed.

### CODE REVIEW

**Comment by mchyzer** [comment]
Does this select the node on create only,  or whenever an object is viewed?  We don't want to change the menu unless an object is  created.  Should we refresh and select parent folder if object deleted?

**Comment by mmoayyed** [comment]
It does both. Why wouldnt you want to change the menu if a object is viewed? Makes sense to me that the view stays with the active selection. 

Good suggestion on removals. I'll run some more tests to see how deletes behave.

**Comment by mmoayyed** [comment]
Tested deletes as well. Works good.

**Comment by mchyzer** [comment]
I think people will be used to left hand menus like windows explorer where the view doesn’t jump around to where you are on the right, it stays on what you have expanded on the left.   Maybe we could have a button like on Eclipse where you can sync them up…  Seems like better performance too right?  Don’t have to have a bunch of ajax requests for each view?

Thanks,
Chris

**Comment by mmoayyed** [comment]
Ah I see. Sure. Well, in that case all I have to do is remove the JS call from the JSP pages and subsequently, have to then call the JS call when new folder/group/attrDef is created and pass along the item id. I'll work on this bit later today.

I think we already have the button. The double arrows can either reload the entire list, or sync with the active view? That would be less confusing.

**Comment by mchyzer** [comment]
I have examples of calling a script from java… I guess should call it if someone moves or copies an object too?  I don’t know, should we ask for others opinions before making it too complicated?

**Comment by mmoayyed** [comment]
So, the more we add to possible use cases the more I am more inclined to use the existing pull behavior that is based on url parameters. So long as the right params exist in the url, the vew will render fine regardless of the original trigger (copy/move/add) that originated it. There will some heavy rest calls, sure, but perhaps we could cache those on the server side.

Happy to consult other opinions to see how we can improve this. Post to grouper-user?

**Comment by mchyzer** [comment]
Post to grouper dev and see what people think

<div>-------- Original message --------</div><div>From: Misagh Moayyed <notifications@github.com> </div><div>Date:03/02/2015  11:52 AM  (GMT-05:00) </div><div>To: Internet2/grouper <grouper@noreply.github.com> </div><div>Cc: mchyzer <mchyzer@isc.upenn.edu> </div><div>Subject: Re: [grouper] auto select the folder/group/attrdef in the view (#26) </div><div>
</div>So, the more we add to possible use cases the more I am more inclined to use the existing pull behavior that is based on url parameters. So long as the right params exist in the url, the vew will render fine regardless of the original trigger (copy/move/add) that originated it. There will some heavy rest calls, sure, but perhaps we could cache those on the server side.

Happy to consult other opinions to see how we can improve this. Post to grouper-user?

**Pull request merged**
