### PR TITLE
Checkstyle and Maven project structure

### PR DESCRIPTION
**Pull request by mmoayyed**
This pull request does the following:

1. Adds checkstyle to the maven build to remove unused and redundant imports.
2. Fixes the maven build project structure specially for WS modules
3. Fixes the build.sample properties file to properly reference in WS the grouper directory. 

Forgot to mention that tested this all for both ant and maven builds. All is a go.

### CODE REVIEW

**Comment by mchyzer** [comment]
When we change a bunch of files it makes cherry picking from 2.2 more difficult and comparing the branches also... think we can save the stuff that changes a ton of files until later in the 2.3 release cycle?  :)

Thanks
Chris

**Comment by mmoayyed** [comment]
That's fine with me, but the more these types of changes linger the more difficult it would be to get them merged because the pile will simply grow in the absence of the stuff that checks for these things. The sooner you do this the better. 

We could also designate someone as a "release engineer" to do the cherry picking. That might remove some of the burden?

I am OK with CS changes hanging, but the bits about maven projects need to go in preferably, so we can generate proper javadocs. I can propose a separate pull for those.

**Comment by mchyzer** [comment]
Lets do this before releasing 2.3, wait until 2.2 has settled down a lot... at least the changes that change a lot of files....

**Comment by mmoayyed** [comment]
sounds good to me.

**Pull request closed without merging**
