### PR TITLE
Feature/grouper 358 replace deprecated security classes

### PR DESCRIPTION
**Pull request by nick-manasys**

### CODE REVIEW

**Comment by cer28** [comment]
What Java version is on your build server? Were these classes the only issues?

**Comment by nick-manasys** [comment]
> What Java version is on your build server? Were these classes the only issues?

We are using Java 1.8 for building and running grouper. These were not the only issues.

I made this minor change as the classes replaced have been deprecated since Java 1.4 and the changes are independent of other code.

**Comment by cer28** [comment]
The change checks out ok. But there are unrelated commits in this PR; the only relevant commit is edfd572. Ok if I cherry pick it and then close this? The commit would still show you as the author

**Comment by cer28** [comment]
There were extraneous commits in this PR, making it hard to merge. The commit edfd572, which had the actual content, was cherry picked into master and verified.

**Pull request closed without merging**
